[platformio]
description = Laser Cutter Revision - Elektronik & Dokumentation
# Setze das Standard-Verzeichnis für den Build auf den Elektronik-Ordner
default_envs = docs_only

[env:docs_only]
# Wir nutzen einen generischen Rahmen, damit PIO die Scripte ausführt
platform = native
# Das Herzstück: Dein Automatisierungs-Script
extra_scripts = post:scripts/generate_diagrams.py