vars: {
  d2-config: {
    layout-engine: elk
  }
}

direction: right

# 1. Styles zentral definieren
classes: {
  kabel_standard: {
    style: { stroke: "#000000"; stroke-width: 3 }
  }
  kabel_orange: {
    style: { stroke: "#e67e22"; stroke-width: 3 }
  }
  widerstand: {
    shape: parallelogram
    style.fill: "#9b59b6"
  }
  jumper: {
    shape: parallelogram
    style.fill: "#f1c40f"
  }
  pin: {
    shape: rectangle
    # Feste Dimensionen garantieren identische Kreise
    width: 80
    height: 40
    style: {
      font-size: 14
    }
  }
}

# Ruida Controller
Ruida_644: {
  shape: package
  label: "Ruida RDC644G/S"
  style: { stroke: "#007AFF"; stroke-width: 3 }

  # General /Dedicated Output Port CN1
  CN1: {
    "1: GND": { class: pin }
    "2: OUT2": { class: pin }
    "3: OUT1": { class: pin }
    "4: STATUS": { class: pin }
    "5: WIND": { class: pin }
    "6: +24V": { class: pin }
  }

  # General /Dedicated Input Port CN2
  CN2: {
    "1: GND": { class: pin }
    "2: FOOTSW": { class: pin }
    "3: DRPROC": { class: pin }
    "4: SHOT": { class: pin }
    "5: IN1": { class: pin }
    "6: +24V": { class: pin }
  }

  # 4-axis limit Input Interface CN3/CN4
  CN3: {
    "1: GND": { class: pin }
    "2: LMTU-": { class: pin }
    "3: LMTU+": { class: pin }
    "4: LMTZ-": { class: pin }
    "5: LMTZ+": { class: pin }
    "6: +5V": { class: pin }
  }

  # 4-axis limit Input Interface CN3/CN4
  CN4: {
    "1: GND": { class: pin }
    "2: LMTY-": { class: pin }
    "3: LMTY+": { class: pin }
    "4: LMTX-": { class: pin }
    "5: LMTX+": { class: pin }
    "6: +5V": { class: pin }
  }

  # X/Y/Z/U-axis Motor Driver Interface AXIS_X~AXIS_U
  AXISX: {
    "1: DIR_X": { class: pin }
    "2: PUL_X": { class: pin }
    "3: +5V_X": { class: pin }
  }

  # X/Y/Z/U-axis Motor Driver Interface AXIS_X~AXIS_U
  AXISY: {
    "1: DIR_Y": { class: pin }
    "2: PUL_Y": { class: pin }
    "3: +5V_Y": { class: pin }
  }
  
  # X/Y/Z/U-axis Motor Driver Interface AXIS_X~AXIS_U
  AXISZ: {
    "1: DIR_Z": { class: pin }
    "2: PUL_Z": { class: pin }
    "3: +5V_Z": { class: pin }
  }

  # X/Y/Z/U-axis Motor Driver Interface AXIS_X~AXIS_U
  AXISU: {
    "1: DIR_U": { class: pin }
    "2: PUL_U": { class: pin }
    "3: +5V_U": { class: pin }
  }

  # Laser Power Control Interface CN5/CN6
  CN5: {
    "1: GND": { class: pin }
    "2: L-ON1": { class: pin }
    "3: LPWM1": { class: pin }
    "4: WP1": { class: pin }
    "5: L-AN1": { class: pin }
  }

  # Laser Power Control Interface CN5/CN6
  CN6: {
    "1: GND": { class: pin }
    "2: L-ON2": { class: pin }
    "3: LPWM2": { class: pin }
    "4: WP2": { class: pin }
    "5: L-AN2": { class: pin }
  }
}

# Verbindungen zur Laser PSU
Ruida_644.CN5.GND -> Laser_PSU.GND: "GND" {class: kabel_standard}
Ruida_644.CN5.L-ON1 -> Laser_PSU.TL: "Laser-Fire" {class: kabel_standard}
Ruida_644.CN5.LPWM1 -> Laser_PSU.IN: "PWM" {class: kabel_standard}


# Bauteile
Resistor_10k_test: 10k { class: widerstand }
Ruida_644.CN5.GND -- Resistor_10k_test { class: kabel_standard }
Ruida_644.CN6.GND -- Resistor_10k_test { class: kabel_standard }

# Laser PSU
Laser_PSU: {
  shape: package
  "5V": { shape: circle }
  IN: { shape: circle }
  TL: { shape: circle }
  WP: { shape: circle }
  TH: { shape: circle }
  GND: { shape: circle }
}

# Bauteile
Bruecke_Laser_IN_5V: 0R { class: jumper }
Resistor_10k_Laser_IN_WP: 10k { class: widerstand }
Resistor_10k_Laser_TH_GND: 10k { class: widerstand }

# Verbindungen
Laser_PSU.IN -- Resistor_10k_Laser_IN_WP { class: kabel_standard }
Laser_PSU.WP -- Resistor_10k_Laser_IN_WP { class: kabel_standard }

Laser_PSU.TH -- Resistor_10k_Laser_TH_GND { class: kabel_standard }
Laser_PSU.GND -- Resistor_10k_Laser_TH_GND { class: kabel_standard }

Laser_PSU.IN -- Bruecke_Laser_IN_5V { class: kabel_standard }
Laser_PSU.5V -- Bruecke_Laser_IN_5V { class: kabel_standard }